[project]
authors = ["igi-111"]
description = "A simple VRF library for Sway"
entry = "lib.sw"
license = "MIT"
name = "vrf"
version = "0.1.2"
repository = "https://github.com/IGI-111/vrf"

[dependencies]
